version: '3'
services:  
  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27017:27017
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    # image: jalas:1
    ports:
      - 3000:3000
      - 8085:8085
      - 3001:3001
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    restart: always
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
        # - gateway: 10.5.0.1