# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mongo:4.2.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install pm2
          command: sudo npm install -g pm2

      - run:
          name: install node modules
          command: yarn install

      - run:
          name: run services
          command: cd backend/packages && pm2 start service-runner.json && cd -

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  unit-test:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:4.2.1

    steps:
      - checkout

      - run:
          name: install node modules
          command: yarn install

      - run: yarn utest

  integration-test:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:4.2.1

    steps:
      - checkout

      - run:
          name: install node modules
          command: yarn install

      - run: yarn itest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - unit-test
